baseURL = "https://oxolll.github.io/"
languageCode = "zh-tw"
title = "My Research Notes"
theme = "PaperMod"

[params]
    # 開啟數學公式支援 (MathJax)
    math = true

    # 預設主題模式 (可選 dark, light, auto)
    defaultTheme = "auto"

    # 顯示目錄 (Table of Contents)
    ShowToc = true